# Generated by Django 3.2.6 on 2021-08-17 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='descount_price',
            new_name='discount_price',
        ),
    ]
