# Generated by Django 3.2.6 on 2021-08-12 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_rename_sales_sale'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sale',
            old_name='Order',
            new_name='order',
        ),
    ]
