# Generated by Django 3.2.6 on 2021-08-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('subject', models.CharField(max_length=50)),
                ('message', models.CharField(max_length=254)),
            ],
        ),
    ]
